<a href="https://colab.research.google.com/github/kartik2627/Artificial-neural-network/blob/main/numpypandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
(7,)

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2))
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2 = np.array(([1,2,3],[4,5,6]))
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

In [ ]:
np.arrange(0,10)

In [2]:
import numpy as np
array_1 = np.arange(0,10)
print(array_1)
array_2 = np.arange(0,10,2)
print(array_2)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]

In [3]:
array_0 = np.zeros((3,3,3))
print(array_0)
print(type(array_0))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>

In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
int64

In [9]:
array_1 = np.array(([1,2,3,4,5]))
array_2 = np.array(([6,7,8,9,10]))
print(array_1)
print(array_2)
print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]

In [10]:
arr = np.array([2,4,6,8])
print(np.sqrt(arr))
print(np.log(arr))
print(np.sin(arr))

[1.41421356 2.         2.44948974 2.82842712]
[0.69314718 1.38629436 1.79175947 2.07944154]
[ 0.90929743 -0.7568025  -0.2794155   0.98935825]

In [12]:
array = np.array([[1,2,3,4,5],[6,7,8,9,0],[10,11,12,13,14]])
print(array)
print(array.shape)
print(array.size)
print(array.ndim)
print(array.dtype)
print(array.reshape(5,3))

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [10 11 12 13 14]]
(3, 5)
15
2
int64
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 10 11]
 [12 13 14]]

In [13]:
arr[0]

2

In [14]:
array[0]

array([1, 2, 3, 4, 5])

In [15]:
array[0][0]

1

In [16]:
print(array[0:2,0:2])
print(array[0:3,0:2])
print(array[0:3,0:3])

[[1 2]
 [6 7]]
[[ 1  2]
 [ 6  7]
 [10 11]]
[[ 1  2  3]
 [ 6  7  8]
 [10 11 12]]

In [17]:
array[100:]
print(array[0:3,0:3])

[[ 1  2  3]
 [ 6  7  8]
 [10 11 12]]

In [18]:
data = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(data)
mean = np.mean(data)
print(mean)
median = np.median(data)
print(median)
std = np.std(data)
print(std)
var = np.var(data)
print(var)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
22.5
22.5
8.241156876717412
67.91666666666667

In [19]:
import pandas as pd

In [20]:
import numpy as np

In [22]:
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [23]:
data = [1,2,3,4,5]
series = pd.Series(data,index=['a','b','c','d','e'])
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [24]:
data = {'a':1,'b':2,'c':3,'d':4,'e':5}
series = pd.Series(data)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [25]:
data = {'a':1,'b':2,'c':3,'d':4,'e':5}
series = pd.Series(data,index=['e','d','c','b','a'])
print(series)

e    5
d    4
c    3
b    2
a    1
dtype: int64

In [26]:
data = [1,2,3,4,5,6,7,8,9]
index = ['a','b','c','d','e','f','g','h','i']
series = pd.Series(data,index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int64

In [29]:
import pandas as pd

data = {
    'Name': ['Kartikay', 'Kritika', 'Ankit', 'Sneha'],
    'Age': [21, 21, 22, 22],  # Using list instead of set
    'City': ['Rehan', 'Nahan', 'Rehan', 'Jammu']
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

# Displaying the first 5 rows
print(df.head())

# Displaying the last 5 rows
print(df.tail())

# Displaying the first 2 rows
print(df.head(2))

# Displaying the last 2 rows
print(df.tail(2))

       Name  Age   City
0  Kartikay   21  Rehan
1   Kritika   21  Nahan
2     Ankit   22  Rehan
3     Sneha   22  Jammu
       Name  Age   City
0  Kartikay   21  Rehan
1   Kritika   21  Nahan
2     Ankit   22  Rehan
3     Sneha   22  Jammu
       Name  Age   City
0  Kartikay   21  Rehan
1   Kritika   21  Nahan
2     Ankit   22  Rehan
3     Sneha   22  Jammu
       Name  Age   City
0  Kartikay   21  Rehan
1   Kritika   21  Nahan
    Name  Age   City
2  Ankit   22  Rehan
3  Sneha   22  Jammu

In [30]:
data = pd.read_csv('/content/sales_data.csv')
data

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [32]:
data.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [33]:
data.tail()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [34]:
data.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [36]:
import pandas as pd
df = pd.read_csv('/content/data.csv')
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [38]:
df.tail()

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [39]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [40]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [41]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [42]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [43]:
df_filled = df.fillna(0)

In [45]:
df['sales_fillna']=df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  sales_fillna
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [46]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
sales_fillna    float64
dtype: object

In [47]:
df=df.rename(columns={'Sales':'sales'})
df

          Date Category  Value   Product  sales Region  sales_fillna
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [48]:
df['Value_new']=df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

         Date Category  Value   Product  sales Region  sales_fillna  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26

In [49]:
df['New Value']=df['Value'].apply(lambda x:x*2)
df.head()

,Date,Category,Value,Product,sales,Region,sales_fillna,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [50]:
grouped_mean=df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [51]:
grouped_sum=df.groupby(['Product','Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [52]:
grouped_sum=df.groupby(['Product','Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [53]:
df.groupby(['Product','Region'])['Value'].mean()

Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [54]:
groudped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
groudped_agg

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [55]:
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [56]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [57]:
pd.merge(df1,df2,on="Key",how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [58]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0